# Site settings
title: Heavy Goods Vehicle Points of Interest
email: bob@hgvpoi.uk
description: > # this means to ignore newlines until "baseurl:"
  Points of Interest for lorry (Heavy Goods Vehicle) drivers
  in the UK
baseurl: ""
url: "https://hgvpoiuk.github.io"
github_username:  hgvpoiuk

# Handling Reading
include: ["_pages", "_poi"]

# Build settings
markdown: kramdown

 
collections:
  poi:
    output: true
    permalink: /poi/:name:output_ext
  posts:
    output: true
    permalink: /:year/:title:output_ext
